### ISSUE TITLE
关于同一个消息只显示一个的问题.

### ISSUE THREAD

**Issue by ohyes666** [MrLiKH/supercustomtoast#1]
您好,这个项目的效果非常赞.
但是在用的时候,有些问题,我并不能解决.
一个是如何判断 一个toast已经显示了,在下一个msg相同的情况下,一定时间不显示新的toast.如果同样的消息,在两次显示时间差大于duration的情况下,才出现新的toast就好了.
第二个是在activity 消失的时候,toast可以也消失掉吗
期待您的回复,谢谢

**Comment by MrLiKH** [comment]
好的 今天刚看到 有时间尽快看一下

**Comment by ohyes666** [comment]
@MrLiKH 
目前我在你的代码中添加了这样的方法,但是效果不是特别好,有的时候会快速的出现两条,activity结束后马上消失的问题也没解决.
        private static String oldMsg = null;
    private static long oneTime = 0;
    private static long twoTime = 0;
public void showOnlyOne(String msg, Long duration, Animation startAnim, Animation endAnim) {
        if (mView.getChildCount() == 1) {
            show(getTextView(msg), duration, startAnim, endAnim);
            oldMsg = msg;
            oneTime = System.currentTimeMillis();
        } else {
            twoTime = System.currentTimeMillis();
            if (msg.equals(oldMsg)) {
                if (twoTime - oneTime > TIME_DURATION) {
                    show(getTextView(msg), duration, startAnim, endAnim);
                }
            } else {
                oldMsg = msg;
                show(getTextView(msg), duration, startAnim, endAnim);
            }
        }
        oneTime = twoTime;
    }

**Comment by MrLiKH** [comment]
@a120200793 
已经解决 
时间仓促，可能不是很优雅，你有什么好的修改方案可以提一下。
至于重复信息的修改，我改在了“自定义5秒”的那个按钮，你试验一下；
谢谢你的修改意见。

**Comment by ohyes666** [comment]
@MrLiKH 3Q啦,效果不错的.感谢您的分享和解答.

**Comment by ZhangPengchao** [comment]
真牛逼
